//Brian Donnelly
//4/20/2021
//Final Assignment Jenkinsfile

pipeline {
    agent any
    parameters {
        booleanParam(name: 'RUN', defaultValue: false, description: 'Whether to Run the Code')

        string(name: 'BUILD_NAME', defaultValue: 'Latest', description: 'Name of the build')
    }
    stages {
        stage('Build') {
            steps {
                echo 'Starting Build...'
                sh 'mvn -B -DskipTests clean install'
                echo 'Build Complete.'
                }
            }
        stage('Code Quantity') {
            steps {
                sh 'wc -l src/main/java/com/mycompany/app/App.java'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Run') {
            when {
                expression { return params.RUN }
            }
            steps {
                sh './ci/deliver.sh'
            }
        }
        stage('Build Results') {
            steps {
                echo "Build ${params.BUILD_NAME} completed successfully."
                echo 'I have now completed ACIT 4850!'
                echo 'Brian Donnelly (A00979287): Group 39'
            }
        }
    }
}
